-- Decompiled using luadec 2.0.2 by sztupy (http://winmo.sztupy.hu)
-- Command line was: C:\Users\pacmanninja998\Downloads\luadec51_2.0.2_win32\decode\Content\Game\DourTower\Rooms\PrincessChambers.lua 

local Class = require("Class")
local Room = require("Room")
local PrincessChambers = Room.classFromLayout("Content/Game/DourTower/Layouts/PrincessChambers", "PrincessChambers", "Content/Game/Global/Rooms/GameRoom")
local Direction = require("Direction")
local Entity = require("Entity")
local CollisionArea = require("CollisionArea")
local Math = require("DFCommon.Math")
local Music = require("Music")
local SceneComponent = require("Components.SceneComponent")
PrincessChambers.onInit = function(l_1_0)
  l_1_0:defineCollisionExit("DRMRoof exit", "Content/Game/DourTower/Rooms/DRMRoof", "PrincessChambers exit")
  if not l_1_0:getState().sawEnding then
    l_1_0:defineLogicTrigger("Ending trigger", l_1_0.onEndingTrigger, l_1_0)
  else
    l_1_0:getCollisionArea("Ending trigger"):setActive(false)
  end
  l_1_0:enableWater()
  Music:playMusic("Music/Music/Princess_Chamber")
end

PrincessChambers.onAliceCreated = function(l_2_0, l_2_1)
  Class.super(PrincessChambers).onAliceCreated(l_2_0, l_2_1)
  l_2_0.fadeEvent:register(l_2_0.onFade, l_2_0)
end

PrincessChambers.onFade = function(l_3_0, l_3_1, l_3_2)
  if l_3_1 == l_3_0.FADE_IN and not l_3_2 then
    local alice = l_3_0:getAlice()
    do
      if l_3_0:getState().sawEnding and not l_3_0:getState().bobPondered then
        alice:get(SceneComponent):play(function(l_1_0)
        local bobPortrait = l_1_0:addCharacter("Portraits/Bob/Bob")
        alice:halt(true)
        l_1_0:speakLineRight(bobPortrait, "So what do we do now?", "Excited")
        alice:halt(false)
         end)
        l_3_0:getState().bobPondered = true
      end
    end
  end
end

PrincessChambers.onEndingTrigger = function(l_4_0)
  local alice = l_4_0:getAlice()
  alice:get(SceneComponent):play(function(l_1_0)
    local alicePortrait = l_1_0:addAlicePortrait()
    local bobPortrait = l_1_0:addCharacter("Portraits/Bob/Bob")
    local florentinePortrait = l_1_0:addCharacter("Portraits/Princess/Princess")
    alice:halt(true)
    l_1_0:speakLineRight(florentinePortrait, "You're here.", "OMG")
    l_1_0:speakLineLeft(bobPortrait, "We win!  Hurray!", "Sing")
    l_1_0:speakLineLeft(alicePortrait, "You know who I am?", "Spooked")
    l_1_0:speakLineRight(florentinePortrait, "Hah. Yes. I am you.", "Crazy")
    l_1_0:speakLineLeft(alicePortrait, "Excuse me?", "Talk2")
    l_1_0:speakLineRight(florentinePortrait, "Have we dealt with Christo?", "Default")
    l_1_0:speakLineLeft(alicePortrait, "Yeah, but I'm more concerned with why you're me.", "Talk")
    l_1_0:speakLineLeft(bobPortrait, "She isn't me.  So she's probably not some kind of strange id projection where we only see ourselves.", "Judgemental")
    l_1_0:speakLineRight(florentinePortrait, "Indeed I am not.  Need we delve into this?  I suspect I've been imprisoned quite a while.", "Hmm")
    l_1_0:speakLineLeft(alicePortrait, "Yeah.  Start delving.", "Default4")
    l_1_0:speakLineRight(florentinePortrait, "...Very well.  We've earned it, I suppose.", "Talk2")
    l_1_0:speakLineRight(florentinePortrait, "I am Florentine, Princess and rightful heir to the kingdom.", "Default")
    l_1_0:speakLineRight(florentinePortrait, "Christo, the Wizard, had ingrained himself in the business of the castle and befriended my father, the King.", "Hmm")
    l_1_0:speakLineRight(florentinePortrait, "When I discovered I had the ability to bond with a red sprite--you do understand the significance of the red sprite, don't you?", "Talk")
    l_1_0:speakLineLeft(bobPortrait, "Nope!", "Talk3")
    l_1_0:speakLineLeft(alicePortrait, "More or less.", "NonPlussed")
    l_1_0:speakLineRight(florentinePortrait, "By the Wizard's will and power, the red sprite is the key to the algorithm rooms.", "Default")
    l_1_0:speakLineRight(florentinePortrait, "He saw me as a threat to his...uniqueness.", "Mad")
    l_1_0:speakLineRight(florentinePortrait, "Using his powers, he manufactured monsters in the woods and brought them to war against the kingdom.", "Asleep")
    l_1_0:speakLineLeft(alicePortrait, "Do I talk this much?", "Default2")
    l_1_0:speakLineLeft(bobPortrait, "You're taciturn to the point of being rude.", "Default")
    l_1_0:speakLineLeft(alicePortrait, "Hey!", "Laughing")
    l_1_0:speakLineRight(florentinePortrait, "When the monsters attacked, my father was terribly wounded.", "WTF")
    l_1_0:speakLineRight(florentinePortrait, "Father abdicated power to the Wizard before he died.", "Hmm")
    l_1_0:speakLineRight(florentinePortrait, "Christo was to turn over the kingdom to me once the danger was past.  Or, presumably, once I showed myself capable of leading the kingdom in such a time.", "Default")
    l_1_0:speakLineRight(florentinePortrait, "He ensured the danger remained, and after he made the castle so impenetrable that I could be hidden away, he imprisoned me in this timeless place.", "Mad")
    l_1_0:speakLineLeft(alicePortrait, "You're not really addressing my question.", "Talk2")
    l_1_0:speakLineRight(florentinePortrait, "I'm just coming to that.", "Hmm")
    l_1_0:speakLineRight(florentinePortrait, "I anticipated Christo's treachery; I was rapidly coming to have the same knowledge as he, and by no magical means.  He was clearly a fraud.", "Default")
    l_1_0:speakLineRight(florentinePortrait, "After he failed to dispose of Isis, the scientist and his former mentor--he did fail, didn't he?", "Talk")
    l_1_0:speakLineLeft(alicePortrait, "She saw it coming too, and made it to a back-up lab.", "Snobby")
    l_1_0:speakLineLeft(bobPortrait, "She's got a cat!", "Excited")
    l_1_0:speakLineRight(florentinePortrait, "Good.  After that, I knew he would come for me soon enough.", "Default")
    l_1_0:speakLineRight(florentinePortrait, "I found myself in the library and made a copy. With some minor tweaks.", "Crazy")
    l_1_0:speakLineLeft(alicePortrait, "...oh bits...", "Spooked")
    l_1_0:speakLineRight(florentinePortrait, "That copy was you. Us.", "OMG")
    l_1_0:speakLineRight(florentinePortrait, "I knew you would save me, because I would.", "Default")
    self:insertPostEffect(self.fadeOutShader)
    l_1_0:animate(2, function(l_1_0)
      self.fadeOutShader:setFragmentUniformFloat("shaderDuration", Math.lerp(0, 1, l_1_0))
      end)
    l_1_0:sleep(0.5)
    l_1_0:speakLineLeft(bobPortrait, "And so the princess went on, explaining the history of the kingdom.", "Default")
    l_1_0:speakLineLeft(bobPortrait, "To be honest, I kind of lost track.", "Sly")
    l_1_0:speakLineLeft(bobPortrait, "But that was the end of our first great adventure.", "Excited")
    l_1_0:animate(0.5, function(l_2_0)
      self.fadeOutShader:setFragmentUniformFloat("shaderDuration", Math.lerp(1, 0, l_2_0))
      end)
    l_1_0:speakLineLeft(alicePortrait, "Uh, $BOB?  You're monologuing.  Out loud.", "NonPlussed")
    l_1_0:speakLineRight(bobPortrait, "Well duh.  How else are you supposed to do it?", "Talk3")
    l_1_0:speakLineLeft(florentinePortrait, "...", "Hmm")
    l_1_0:animate(0.5, function(l_3_0)
      self.fadeOutShader:setFragmentUniformFloat("shaderDuration", Math.lerp(0, 1, l_3_0))
      end)
    l_1_0:sleep(0.2)
    l_1_0:speakLineRight(bobPortrait, "But that is not the end of our story.", "Angry")
    l_1_0:speakLineRight(bobPortrait, "$ALICE and Florentine went on to rule the kingdom with a deft hand.", "Default")
    l_1_0:speakLineRight(bobPortrait, "Err. Deft hands.", "Sly")
    l_1_0:speakLineRight(bobPortrait, "We freed the prisoners, and maintained very low recidivism rates.", "Excited")
    l_1_0:animate(0.5, function(l_4_0)
      self.fadeOutShader:setFragmentUniformFloat("shaderDuration", Math.lerp(1, 0, l_4_0))
      end)
    l_1_0:speakLineLeft(alicePortrait, "Good idea. We should go do that.", "Default3")
    l_1_0:speakLineRight(florentinePortrait, "I agree. ...wait, is he still going?", "Talk2")
    l_1_0:animate(0.5, function(l_5_0)
      self.fadeOutShader:setFragmentUniformFloat("shaderDuration", Math.lerp(0, 1, l_5_0))
      end)
    l_1_0:speakLineRight(bobPortrait, "And I became the king of the sprites!", "Happy")
    l_1_0:speakLineLeft(alicePortrait, "I don't think that's going to happen.", "DopeySmile")
    l_1_0:speakLineRight(bobPortrait, "But most importantly, I repaired the damage to the kingdom--", "Default")
    l_1_0:speakLineLeft(alicePortrait, "$BOB, if you wrap it up, we could actually go do some of these things.", "Talk2")
    l_1_0:speakLineRight(bobPortrait, "--and made lifelong friends.", "Sly")
    l_1_0:speakLineLeft(alicePortrait, "The end?", "Default3")
    l_1_0:speakLineRight(bobPortrait, "The End.", "Cute")
    l_1_0:displayTitleCard(15, "<c:72FEFDFF>HACK 'N' SLASH TEAM</></title>\nBrandon Dillon                                 Project Lead\nMatt Hansen                              Executive Producer\nSu Liu                                   Assistant Producer\nDuncan Boehle                      Lead Gameplay Programmer\nPaul Du Bois                         Additional Programming\nMark Hamer                     Art Director / Lead Animator\nRazmig Mavlian      Background Designer / Background Artist\nSay Oh                                               Artist\nRay Crook                                          Animator\nLydia Choy                      VFX Artist / Voice of Alice\nErin Eldridge                                        Writer\nPaul O'Rourke                     Sound Designer / Composer\nBrian Correia                              Additional Audio\nAnthony Banks                                     QA Tester\nTony Lo                                           QA Tester\nVictor Romero                                     QA Tester<title>\n")
    l_1_0:displayTitleCard(15, "<c:72FEFDFF>DOUBLE FINE PRODUCTIONS</></title>\nTim Schafer\t                              President and CEO\nJustin Bailey                                          COO\nIsa Stamos                               VP of Development\nGreg Rice                        Senior Publishing Manager\nDaniel Pangelina                                QA Manager\nBrian Min                                   Audio Director\nChris Remo                                 Web Development\nAmarisse Sullivan                     Office Administrator\nDenise Gollaher                         Operations Manager\nBarry Drake                                     Accountant\nJustin Honegger                         Desktop Technician\nAaron Hayes                               Tech Ops Manager\nAdrian Melian                                  Studio Tech\nOliver Franzke                                 Studio Tech\nPaul Du Bois                                   Studio Tech<title>\n")
    l_1_0:displayTitleCard(10, "<c:72FEFDFF>HACK 'N' SLASH\nWAS MADE POSSIBLE BY</></title>\n\nIndie Fund\nHumble Bundle\nHemisphere Games\nmake all LLC\nAppAbove Games\nAdam and Rebekah Saltsman\nThe Behemoth\nMorgan Webb\nRob Reid<title>\n")
    l_1_0:displayTitleCard(2, "<c:72FEFDFF>THE TEAM WOULD LIKE TO THANK</>")
    l_1_0:displayTitleCard(5, "</>Max\nDale\nStormtrooper\nTeebo\nRancor\nMochi\nRosco\nCadet\nKuma\nWaffle<title>")
    l_1_0:displayTitleCard(5, "</>Mark Boehle\nLisa Boehle\nAnna Boehle<title>")
    l_1_0:displayTitleCard(5, "</>Michele and Ruby</title>")
    l_1_0:displayTitleCard(5, "</>Razmig Mavlian would like to thank everyone<title>")
    l_1_0:displayTitleCard(5, "</>Mary Hull\nSarah Hull\nBrad Hull\nRon O'Rourke\nAndrew O'Rourke\nTony O'Rourke<title>")
    l_1_0:displayTitleCard(5, "</>Roger Hansen\nSandi Hansen\nAndrew Hansen\nKristen Russell\nFleury\nOtis McGoaterson\nStatsy \"Mr. S\"<title>")
    l_1_0:displayTitleCard(5, "</>Mom\nDad\nDrew Skillman\nShawn Choy<title>")
    l_1_0:displayTitleCard(5, "</>NOKturne\nChance<title>")
    l_1_0:displayTitleCard(5, "</>Hongying Lin\nTao Liu\nReed and friends<title>")
    l_1_0:displayTitleCard(5, "</>Crystal and Ares<title>")
    l_1_0:displayTitleCard(5, "</>Keri\nTia (Cake)\nTerra (Kicks)\nJack C. Bailey<title>")
    l_1_0:displayTitleCard(5, "</>Barb and Tim Rice\nCari\nMatt\nAdaline Friesleben<title")
    l_1_0:displayTitleCard(5, "</>Derek Brand\nChris Schultz\nMalena Annable\n\nfor their help on the original AF prototype<title>")
    l_1_0:displayTitleCard(5, "</>\n<c:72FEFDFF>Shannon</>\nMatt Alderman\n#shenanigans<title>")
    l_1_0:displayTitleCard(5, "</>All of Double Fine's Awesome Fans<title>")
    l_1_0:displayTitleCard(15, "<c:72FEFDFF>SPECIAL THANKS</></title>\nFangamer\n2 Player Productions\nThe entire team at Double Fine Productions\n\nFMOD Ex Sound System\nCopyright \194\169 2001-2014 Firelight Technologies Pty, ltf.\nAll rights reserved.<title>")
    self:getState().sawEnding = true
    self:universe().state:addCheckpoint("The End")
    alice.host.completeTheGame = true
   end)
end

return PrincessChambers

