-- Decompiled using luadec 2.0.2 by sztupy (http://winmo.sztupy.hu)
-- Command line was: C:\Users\pacmanninja998\Downloads\luadec51_2.0.2_win32\decode\Content\Game\DourTower\Rooms\Staircase1.lua 

local Class = require("Class")
local Room = require("Room")
local Staircase1 = Room.classFromLayout("Content/Game/DourTower/Layouts/Staircase", "Staircase1", "Content/Game/DourTower/Rooms/Staircase")
local Entity = require("Entity")
local Math = require("DFCommon.Math")
local Music = require("Music")
local Shader = require("Shader")
local SceneComponent = require("Components.SceneComponent")
local SoundComponent = require("Components.SoundComponent")
Staircase1.onInit = function(l_1_0)
  Class.super(Staircase1).onInit(l_1_0)
  l_1_0:defineCollisionExit("Exit_Lft", "Content/Game/DourTower/Rooms/TowerLevel1", "Staircase1 exit")
  l_1_0:defineCollisionExit("Exit_Rt", "Content/Game/DourTower/Rooms/TowerLevel2", "Staircase1 exit")
end

Staircase1.onEntranceTrigger = function(l_2_0)
  if l_2_0:getState().sawMonologue then
    return 
  end
  l_2_0:getState().sawMonologue = true
  local alice = l_2_0:getAlice()
  local bob = l_2_0:getBob()
  alice:get(SceneComponent):play(function(l_1_0)
    local alicePortrait = l_1_0:addAlicePortrait()
    local bobPortrait = l_1_0:addCharacter("Portraits/Bob/Bob")
    local head = Entity.create("Content/Game/DourTower/Entities/WizardHead", self:getLayerByOrder(0), alice:getPosition())
    head:trackEntity(alice)
    head:appear()
    local cameraShake = Shader.load("Content/Game/Global/Shaders/CameraShake")
    cameraShake:setFragmentUniformFloat("shaderDuration", 0.6)
    self:insertPostEffect(cameraShake)
    l_1_0:animate(0.5, function(l_1_0)
      cameraShake:setFragmentUniformFloat("shaderDuration", Math.lerp(0.6, 0, l_1_0))
      end)
    self:removePostEffect()
    Music:playMusic("Music/Music/WizardTower_Level5_Layer1")
    head:setFace("Angry")
    l_1_0:floatText(head, "WHO DARES ASCEND MY--oh.", nil, {floatAbove = false})
    head:setFace("Skeptical")
    l_1_0:sleep(0.25)
    l_1_0:floatText(head, "I wasted a hologram on YOU.", nil, {floatAbove = false})
    head:setFace()
    l_1_0:sleep(0.5)
    l_1_0:floatText(bob, "You wasted it on *both* of us.  Can't you teleport anyway?", nil, {floatAbove = false})
    l_1_0:floatText(alice, "Technically, 'you' is still co--", nil, {floatAbove = false})
    self:insertPostEffect(cameraShake)
    local cue = alice:get(SoundComponent):playCue("SFX/Cutscenes/WizardTower_Earthquake")
    head:setFace("Angry")
    l_1_0:animate(0.05, function(l_2_0)
      head.prop:setScl(Math.lerp(1, 1.5, l_2_0))
      cameraShake:setFragmentUniformFloat("shaderDuration", Math.lerp(0, 0.3, l_2_0))
      end)
    l_1_0:floatText(head, "SHUT UP.  You've really crossed the line now.", nil, {floatAbove = false})
    alice:get(SoundComponent):stopCue(cue)
    l_1_0:animate(0.2, function(l_3_0)
      cameraShake:setFragmentUniformFloat("shaderDuration", Math.lerp(0.3, 0, l_3_0))
      end)
    self:removePostEffect()
    head:setFace()
    l_1_0:sleep(0.2)
    l_1_0:floatText(alice, "... --rrect.", nil, {floatAbove = false})
    l_1_0:sleep(0.5)
    head:setFace("Angry")
    l_1_0:floatText(head, "Gah!  You'll never save the princess!  You'll die!", nil, {floatAbove = false})
    head:disappear()
    l_1_0:sleep(1)
    alice:halt(true)
    l_1_0:speakLineLeft(alicePortrait, "Princess?", "Spooked")
    l_1_0:speakLineRight(bobPortrait, "Did we go to the right castle?", "Talk3")
    alice:halt(false)
   end)
end

return Staircase1

