-- Decompiled using luadec 2.0.2 by sztupy (http://winmo.sztupy.hu)
-- Command line was: C:\Users\pacmanninja998\Downloads\luadec51_2.0.2_win32\decode\Content\Game\MachineRooms\Entities\ExpressionMachine.lua 

local Class = require("Class")
local Entity = require("Entity")
local ExpressionMachine = Class.create(Entity, "ExpressionMachine")
local Direction = require("Direction")
local Disassembly = require("Disassembly")
local Font = require("Font")
local PhysicsComponent = require("Components.PhysicsComponent")
local SpriteComponent = require("Components.SpriteComponent")
ExpressionMachine.MACHINE_INFO = {Machine01 = {input 1 = "Tube", input 2 = "Tube", input 3 = "Tube", output = "Right"}, Machine02 = {output = "Right"}, Machine03 = {input 1 = "Tube", input 2 = "Tube", input 3 = "Tube", output = "Right"}, Machine04 = {input 1 = "Left", input 2 = "Right", input 3 = "Left", input 4 = "Right", input 5 = "Left", input 6 = "Right", output = "Top"}, Machine04Return = {input 1 = "Left", input 2 = "Right", input 3 = "Left", input 4 = "Right", input 5 = "Left", input 6 = "Right", output = "Top"}, Machine05 = {input 1 = "Tube", input 2 = "Tube", input 3 = "Tube", output = "Right"}, Machine06 = {output = "Right"}}
{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.MOD] = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.POW] = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.UNM] = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.NOT] = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.LEN] = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.CONCAT] = {machine = "Machine04", operands = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.JMP] = {machine = "Machine06"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.EQ] = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, subclass = "Content/Game/MachineRooms/Entities/EQMachine"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.LT] = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, subclass = "Content/Game/MachineRooms/Entities/LTMachine"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.LE] = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, subclass = "Content/Game/MachineRooms/Entities/LEMachine"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.TEST] = {machine = "Machine06", operands = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/TESTMachine"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.TESTSET] = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}, subclass = "Content/Game/MachineRooms/Entities/TESTMachine"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.CALL] = {machine = "Machine04", operands = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.TAILCALL] = {machine = "Machine04", operands = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.RETURN] = {machine = "Machine04Return", operands = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.FORLOOP] = {machine = "Machine06", operands = {"crystal"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.FORPREP] = {machine = "Machine05", operands = {"input 1", "input 2", "input 3"}, targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.TFORLOOP] = {machine = "Machine03"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.SETLIST] = {machine = "Machine04", operands = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.CLOSE] = {machine = "Machine01"}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.CLOSURE] = {machine = "Machine06", fn = "crystal", targets = {"output"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

{Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}[Disassembly.VARARG] = {machine = "Machine04", targets = {"input 1", "input 2", "input 5", "input 6"}}
 -- DECOMPILER ERROR: Confused about usage of registers!

ExpressionMachine.EXPRESSION_INFO = {Disassembly.MOVE = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADK = {machine = "Machine06", operands = {"crystal"}, targets = {"output"}}, Disassembly.LOADBOOL = {machine = "Machine06", targets = {"crystal"}, subclass = "Content/Game/MachineRooms/Entities/LOADBOOLMachine"}, Disassembly.LOADNIL = {machine = "Machine04", targets = {"input 1", "input 2", "input 3", "input 4", "input 5", "input 6"}}, Disassembly.GETUPVAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETGLOBAL = {machine = "Machine06", targets = {"crystal"}}, Disassembly.GETTABLE = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.SETGLOBAL = {machine = "Machine03", operands = {"input 1", "input 3"}}, Disassembly.SETUPVAL = {machine = "Machine03", operands = {"input 1"}}, Disassembly.SETTABLE = {machine = "Machine01", operands = {"input 1", "input 2", "input 3"}}, Disassembly.NEWTABLE = {machine = "Machine06", targets = {"crystal"}}, Disassembly.SELF = {machine = "Machine05", operands = {"input 1", "input 3"}, targets = {"output"}}, Disassembly.ADD = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.SUB = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.MUL = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}, Disassembly.DIV = {machine = "Machine02", operands = {"crystal 1", "crystal 2"}, targets = {"output"}}}
ExpressionMachine.init = function(l_1_0, l_1_1, l_1_2, l_1_3, l_1_4)
  Class.super(ExpressionMachine).init(l_1_0, l_1_1, l_1_2, l_1_3, l_1_4)
  SpriteComponent.new(l_1_0, "Interactions/Props/CodeRoomHardware/GenericHardware/GenericHardware")
  l_1_0.prop:setScl(0.25)
  l_1_0.prop:forceUpdate()
  l_1_0:setLabelText("")
end

ExpressionMachine.updateLabelText = function(l_2_0)
  l_2_0:setLabelText(l_2_0.expressionLayout:getFormat())
end

ExpressionMachine.setExpressionLayout = function(l_3_0, l_3_1)
  l_3_0.expressionLayout = l_3_1
  l_3_0.expression = l_3_0.expressionLayout.expression
  local expressionInfo = l_3_0.EXPRESSION_INFO[l_3_0.expression:class()]
  local sprite = l_3_0:get(SpriteComponent)
  sprite:setSprite(expressionInfo.machine)
  local x0, y0, x1, y1 = sprite.sheet:getHitbox("body", expressionInfo.machine)
  x0, y0, x1, y1 = x0 * 0.25, y0 * 0.25, x1 * 0.25, y1 * 0.25
  PhysicsComponent.new(l_3_0, {rect = {x0, y0, x1, y1}, category = PhysicsComponent.DYNAMIC_CATEGORY, bodyType = MOAIBox2DBody.STATIC})
  local jointX, jointY = sprite.sheet:getJoint("display", expressionInfo.machine)
  if jointX and jointY then
    l_3_0.label.textBox:setLoc(jointX, jointY)
  end
  l_3_0.expressionLayout.prototypeLayout.prototypeChangedEvent:register(l_3_0.updateLabelText, l_3_0)
  l_3_0:updateLabelText()
  local displayX, displayY = l_3_0.prop:modelToWorld(jointX, jointY)
  displayX = displayX + 3
  l_3_0.display = Entity.create("Content/Game/DourTower/Entities/NamePlaque", l_3_0.layer, displayX, displayY, nil, Direction.DIR_S, l_3_0.expression.instruction:GET_OPCODE_NAME(), 0.15, {1, 1, 1, 1}, 80, Font.TITLE_PATH)
  local enterX, enterY = sprite.sheet:getJoint("N", expressionInfo.machine)
  sprite.prop:setPriority(-enterY * 0.25)
  if l_3_0:isHackable() then
    local hackX, hackY = sprite.sheet:getJoint("hack", expressionInfo.machine)
    local posX, posY = l_3_0.prop:modelToWorld(hackX, hackY, 0)
    Entity.create("Content/Game/MachineRooms/Entities/HackPort", l_3_0.layer, posX, posY)
  end
  if expressionInfo.fn then
    local location = expressionInfo.fn
    local jointX, jointY = sprite.sheet:getJoint(location, expressionInfo.machine)
    local posX, posY = l_3_0.prop:modelToWorld(jointX, jointY, 0)
    local tube = Entity.create("Content/Game/MachineRooms/Entities/Tube", l_3_0.layer, posX, posY)
    local tubeName = l_3_0.MACHINE_INFO[expressionInfo.machine][location]
    tube:setTube(l_3_1.prototypeLayout, tubeName, {l_3_0.expressionLayout.prototypeLayout.functionColorMap[l_3_0.expression.functionIndex]})
  end
  if expressionInfo.operands then
    local operandLocations = #expressionInfo.operands
    local maxCrystalsPerLocation = math.ceil(#l_3_0.expression.operands / operandLocations)
    local operandCursor = 1
    for i,location in ipairs(expressionInfo.operands) do
      local crystalColors = {}
      repeat
        if #crystalColors < maxCrystalsPerLocation and operandCursor <= #l_3_0.expression.operands then
          local operand = l_3_0.expression.operands[operandCursor]
          local operandColor = l_3_0.expressionLayout.prototypeLayout:getOperandColorIndex(operand)
          local override = l_3_1.operandOverrides[operand.index]
          if override then
            operandColor = l_3_0:getPrimaryColor(l_3_1.prototypeLayout, override.expression)
          end
          table.insert(crystalColors, operandColor)
          operandCursor = operandCursor + 1
        elseif #crystalColors ~= 0 then
          local jointX, jointY = sprite.sheet:getJoint(location, expressionInfo.machine)
          local posX, posY = l_3_0.prop:modelToWorld(jointX, jointY, 0)
          local tube = Entity.create("Content/Game/MachineRooms/Entities/Tube", l_3_0.layer, posX, posY)
          local tubeName = l_3_0.MACHINE_INFO[expressionInfo.machine][location]
          tube:setTube(l_3_1.prototypeLayout, tubeName, crystalColors)
        end
      end
    end
    if expressionInfo.targets then
      local targetLocations = #expressionInfo.targets
      local maxCrystalsPerLocation = math.ceil(#l_3_0.expression.targets / targetLocations)
      local targetCursor = 1
      for i,location in ipairs(expressionInfo.targets) do
        local crystalColors = {}
        repeat
          if #crystalColors < maxCrystalsPerLocation and targetCursor <= #l_3_0.expression.targets then
            local target = l_3_0.expression.targets[targetCursor]
            local targetColor = l_3_0.expressionLayout.prototypeLayout:getRegisterColorIndex(target.register, target.version)
            table.insert(crystalColors, targetColor)
            targetCursor = targetCursor + 1
          elseif #crystalColors ~= 0 then
            local jointX, jointY = sprite.sheet:getJoint(location, expressionInfo.machine)
            local posX, posY = l_3_0.prop:modelToWorld(jointX, jointY, 0)
            local monitor = Entity.create("Content/Game/MachineRooms/Entities/Monitor", l_3_0.layer, posX, posY)
            local monitorName = l_3_0.MACHINE_INFO[expressionInfo.machine][location]
            monitor:setMonitor(l_3_1.prototypeLayout, monitorName, crystalColors)
          end
        end
      end
       -- Warning: missing end command somewhere! Added here
    end
     -- Warning: missing end command somewhere! Added here
  end
end

ExpressionMachine.getPrimaryColor = function(l_4_0, l_4_1, l_4_2)
  if l_4_2:is(Disassembly.LOADK) then
    return l_4_1.constantColorMap[l_4_2.instruction:GETARG_Bx()]
  else
    if l_4_2:is(Disassembly.GETGLOBAL) then
      return l_4_1.constantColorMap[l_4_2.instruction:GETARG_Bx()]
    else
      if l_4_2:is(Disassembly.GETUPVAL) then
        return l_4_1.upvalueColorMap[l_4_2.instruction:GETARG_B()]
      else
        if l_4_2:is(Disassembly.MOVE) then
          return l_4_1:getOperandColorIndex(l_4_2.operands[1])
        else
          if l_4_2:is(Disassembly.SELF) then
            return l_4_1:getOperandColorIndex(l_4_2.operands[2])
          else
            local target = l_4_2.targets[1]
            return l_4_1:getRegisterColorIndex(target.register, target.version)
          end
        end
      end
    end
  end
end

return ExpressionMachine

